# Generated by Django 5.0.6 on 2024-05-10 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0002_cbtuser_state_active_alter_cbtuser_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbtuser',
            name='otp',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cbtuser',
            name='otp_time',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
