# Generated by Django 5.0.6 on 2024-05-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0003_cbtuser_otp_cbtuser_otp_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbtuser',
            name='user_code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
